# Generated by Django 6.0.2 on 2026-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobrequestimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='estimated_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
