# Generated by Django 6.0.2 on 2026-04-17 16:33

import cloudinary.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_offer_estimated_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequestimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='image'),
        ),
    ]
